### ISSUE TITLE
Spotify Logo in Low Resolution

### ISSUE THREAD

**Issue by MrManuXZ** [svr333/audio-band#27]
## Suggestion
Change Spotify logo and set it up to a higher resolution one.
![q8qrh7BhvW](https://user-images.githubusercontent.com/45375894/140829272-a8a7ab85-1f5d-47bf-9749-7586fa4ee765.png)

## Spotify Logo Suggestions
![chrome_a9G1eDbWnE](https://user-images.githubusercontent.com/45375894/140830180-faddc1fe-1a0d-4d61-8217-577d61ec0f7a.png)

- https://newsroom.spotify.com/media-kit/logo-and-brand-assets/

## Extra
Set more space between the logo and the album border image.
![cOBF0Noams](https://user-images.githubusercontent.com/45375894/140828885-627b55bb-6c86-47b2-b5da-091f7982b42f.png)

**Comment by svr333** [comment]
I tried to recreate but uh, I dont have any spotify logo
![image](https://user-images.githubusercontent.com/35664724/140830970-8a2522d6-d91d-4539-beac-ed807cfa7ae3.png)

**Comment by svr333** [comment]
The album art is provided by whichever audiosource you are using

**Comment by svr333** [comment]
was able to replicate now, the image provided by the windows 10 api is just very low quality, nothing much I can do about it

If you do not want to see it, you can use Spotify as an audiosource after setting it up, then the black border will go away

**Comment by MrManuXZ** [comment]
> was able to replicate now, the image provided by the windows 10 api is just very low quality, nothing much I can do about it
> 
> If you do not want to see it, you can use Spotify as an audiosource after setting it up, then the black border will go away

I understand, thanks anyway.

I'm okay with it, just trying to help improve the app and make it look more cleaner and nicer.

**Comment by svr333** [comment]
yeah I just double checked, there is no way for me to enhance the quality of the image, sorry :/

But as I said if you only use Spotify I recommend switching to the Spotify Audiosource over the Windows10 one

> I'm okay with it, just trying to help improve the app and make it look more cleaner and nicer.

This is very much appreciated though! Thank you for the feedback
