### ISSUE TITLE
Progress Bar Restarts the Media

### ISSUE THREAD

**Issue by MrManuXZ** [svr333/audio-band#28]
## Description
When I'm listening music, I try to move around with the progress bar and select a specific point of the song I am listening to, and what it happens, is that, the all song gets restarted.

![JSM9fpOJMV](https://user-images.githubusercontent.com/45375894/141160255-56432437-76e3-4614-8508-2c6f83a0a926.gif)

I'm using Windows 10 as audio source.

## How To Reproduce
1. Establish Windows 10 as audio source (Not sure if the same happens with other audio sources)
2. Play some music (I'm using Spotify)
3. Click on Progress Bar and try to select a specific point of a song

## Version
 - Windows version: Windows 10 Pro 1909
 - AudioBand version: v1.0.1

## Log
[AudioBand.log](https://github.com/svr333/audio-band/files/7514536/AudioBand.log)

**Comment by svr333** [comment]
This fix will be present in the next (pre-)release

**Comment by MrManuXZ** [comment]
> This fix will be present in the next (pre-)release

Take your time, thanks.

**Comment by MrManuXZ** [comment]
You the best B).

**Comment by MrManuXZ** [comment]
You the best @svr333 B).

**Comment by svr333** [comment]
Haha thanks
