### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by kotobuki09** [svr333/audio-band#3]
**Describe the bug**

I get an error after added Spotify Client Id and Spotify Client Secret to the Audio Source Settings. 
I used the latest version audio-band. Could you check about his issue?

**Comment by svr333** [comment]
Inside your [Spotify Dashboard](https://developer.spotify.com/dashboard), open up your application, click edit settings and add `http://localhost:80` to your redirect urls
(see image for guidance)

![image](https://user-images.githubusercontent.com/35664724/127001837-e88ba6aa-ae72-4093-8578-4ac6b622c5e1.png)

**Comment by kotobuki09** [comment]
For sure. I already completed this step as your guide!
[https://i.imgur.com/mH3hykr.png](url)

**Comment by svr333** [comment]
Oh I think I made a mistake setting up something, for now you also have to add `http://localhost` to it, I'll patch it in a bit

**Comment by kotobuki09** [comment]
After adding two other lines. It's work well now!
